### ISSUE TITLE
New user registration email template

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber/microweber#670]
The function register_email_send in file `src\Microweber\Providers\UserManager.php` replaces various short codes with user data eg username, and the replace function replaces eg {username} with the user's name. However in the email template the E-mail values button adds field names/shortcodes enclosed in double curly bracket eg `{{username}}` so the test email delivered contains `{Name}` ie with one set of curly brackets remaining. Should there be one set or two sets of curly brackets? I assume just the one (it's not a field in a Symphony template).

**Comment by Ezyweb-uk** [comment]
Why are double curly brackets used to wrap around fields in `function get_mail_template_fields` in file `userfiles\modules\admin\mail_templates\functions.php`, because it breaks the field search and replacement in `function register_email_send` in file `src\Microweber\Providers\UserManager.php` which replaces single curly brackets?

**Comment by daebak74** [comment]
@peter-mw 
I saw the repository changed so impossible to merge. By the way I re-wrote the code of new registration email and the reset password.
@Ezyweb-uk should be fixed the problem with brackets too let me know.
[src.zip](https://github.com/microweber/microweber/files/5154566/src.zip)

**Comment by Starbors** [comment]
Maybe learn how to code+Dont put this website on google https://microweber.org/ is a thing

**Comment by Ezyweb-uk** [comment]
Fixed in v1.2

**Comment by Ezyweb-uk** [comment]
Still exists in 1.2.1 dev 
https://github.com/microweber/microweber/blob/b4932edd3d707c4a6c3659e740a601a07003fa0e/userfiles/modules/admin/mail_templates/functions.php#L59

**Comment by Ezyweb-uk** [comment]
Issue re-introduced in version 1.2.2 - function get_mail_template_fields in file `userfiles\modules\admin\mail_templates\functions.php` with double curly brackets is not compatible with function register_email_send in file `src\MicroweberPackages\User\UserManager.php` line 948 which replaces a single curly brackets, so one set of curly brackets remain after the field merge.
