### ISSUE TITLE
Modul Tabs / Accordion - how to edit / add content

### ISSUE THREAD

**Issue by walhallaRV** [microweber/microweber#936]
### Discussed in https://github.com/microweber/microweber/discussions/935

<div type='discussions-op-text'>

<sup>Originally posted by **walhallaRV** August 22, 2022</sup>
Hi,
I tried to put an accordion / tabs - modul on a site. OK, it works. But I only can add / edit / see the content of the first tab / accordion. I can add more, can see the tabs, but how can I add content to the new tabs / accordions.

Playing around for hours now and can't find how. Becoming realy crazy ;) On the website I can see the accordion / tabs with content in the first tab / accordion. But if i click on any other tab / accordion nothing happens. Doesn't collapse, not change anything.

I tried the same in the Microweber demo - site: there apears  a red pop-up (maybe errors?) but just 1 second and I can read so fast. Same problem: can see the accordion / tabs, can add / see content of the first one. But the rest is unvisible, cant input content.

Thanks so much for your help!

Cheers Walhalla
</div>

**Comment by RogerAntonio** [comment]
I believe I fixed this on my template by rewriting the default template.
Originally the tabs and accordion modules were written for Bootstrap 3 (iirc).
It could be that the templates you are using might have updated to Bootstrap 5 and the module author might not have updated the default template to bootstrap 5 yet.
See the difference here (for accordion):
https://getbootstrap.com/docs/4.6/components/collapse/#accordion-example
https://getbootstrap.com/docs/5.1/components/accordion/#example

**Comment by walhallaRV** [comment]
OK, thank you so much for youre answer. Not a good one - but atleast an answer. Tried to get some information here, other / old forum, facebook, .... but they didnt answer.

I am using the standard template "New World" wich was made by themselfs (MW-Team). So, I cant do nothing. It's a pity, found MW on my search, wanted to give a testdrive ... but unfortunately maybe the ride will end here because it is not working as expected. Was playing around just some minutes, foud this "bug", spent 1 hour because i thought that I'm to stupid to find the way how to add content ;) Further: if you choose an icon for the Tabs / Accordions you get ann server - error. Hummm ...

Thanks a lot for your response! Atleast I know now that I am not to stupid, didnt do anything wrong ;)

**Comment by walhallaRV** [comment]
I forgot: is there a quick & dirty workaround for now? Really want to show MW to the customer. Thx!

**Comment by walhallaRV** [comment]
Hi, after one month still have the same question: will there be an update for this template soon? Thanks for any answer!
